### ISSUE TITLE
Dimension error when scaling wind variable (with ERA5)

### ISSUE THREAD

**Issue by gwib** [geocryology/globsim#82]
Scaling issue seems to arise when trying to scale wind variable from two dimensions (u,v) to one (WSPD_sur)

**Comment by nicholas512** [comment]
also seems to only come up on some configurations (may be an issue with library version for numpy, netcdf4, )

**Comment by nicholas512** [comment]
@gwib  - did you end up looking at this at all?  I know @Johniitr was having trouble scaling data in the docker image, and it was crashing at the wind step.

* Which reanalysis was causing this error (or was it all of them?)
* Can you provide a stack trace?

**Comment by Johniitr** [comment]
@nicholas512 and @gwib - Here is the error message I am getting while running the scaling process for multiple sites (13 in my case). 
```
root@59e17f8c1a7d:/opt/globsim/globsim# python3 globsim_scale.py -d ERA5 -f ../../../data/par/upperg_config.tom1
```
```
PRESS_Pa_pl
AIRT_C_pl
AIRT_C_sur
PREC_mm_sur
RH_per_sur
WIND_sur
Traceback (most recent call last):
File "src/netCDF4/_netCDF4.pyx", line 4931, in netCDF4._netCDF4.Variable.__setitem__
ValueError: cannot reshape array of size 132600 into shape (10200,1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "globsim_scale.py", line 56, in <module>
main(args)
File "globsim_scale.py", line 40, in main
JRA=JRA, MERRA=MERRA)
File "/usr/local/lib/python3.6/dist-packages/globsim-2.1.0-py3.6.egg/globsim/globsim_main.py", line 148, in GlobsimScale
ERA5sc.process()
File "/usr/local/lib/python3.6/dist-packages/globsim-2.1.0-py3.6.egg/globsim/scale/ERA5scale.py", line 150, in process
File "/usr/local/lib/python3.6/dist-packages/globsim-2.1.0-py3.6.egg/globsim/scale/ERA5scale.py", line 124, in indProcess
File "/usr/local/lib/python3.6/dist-packages/globsim-2.1.0-py3.6.egg/globsim/scale/ERA5scale.py", line 307, in WIND_sur
File "src/netCDF4/_netCDF4.pyx", line 4933, in netCDF4._netCDF4.Variable.__setitem__
File "<__array_function__ internals>", line 6, in broadcast_to
File "/usr/local/lib/python3.6/dist-packages/numpy/lib/stride_tricks.py", line 180, in broadcast_to
return _broadcast_to(array, shape, subok=subok, readonly=True)
File "/usr/local/lib/python3.6/dist-packages/numpy/lib/stride_tricks.py", line 125, in _broadcast_to
op_flags=['readonly'], itershape=shape, order='C')
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (10200,13) and requested shape (10200,1)
```
However, If I run the scaling process for a single site, the interpolation and scaling process run smoothly.

**Comment by nicholas512** [comment]
in
```
for n, s in enumerate(self.rg.variables['station'][:].tolist()):
            WS = np.sqrt(np.power(V,2) + np.power(U,2))
            WD = [atan2(V[i, n], U[i, n]) * (180 / pi) +
                  180 for i in np.arange(V.shape[0])]
            self.rg.variables[vn_spd][:, n] = WS
            self.rg.variables[vn_dir][:,n] = WD
```

`WS` definition does not subset wind, (but WD does!) so when writing to `self.rg`, on 4th line, its trying to write the whole array.
Who knows why this worked for some people.
