### ISSUE TITLE
`overwrite=true` is ignored in control file for scaling.  Make it possible to overwrite existing files.

### ISSUE THREAD

**Issue by stgruber** [geocryology/globsim#87]
Scaling is slow and halts when file exists. Alternative handling options: 
1. Check for file existence when scaling starts and ask for decision.
2. Copy old file to incremented name and let new file have the 'proper' name in case this runs in some larger set of experiments.  
3. ...

```
(globsim) stgruber@talik:~/storage/globsim/YK/scaled$ globsim scale -d JRA -f /fs/yedoma/usr-storage/stgruber/globsim/YK/par/ldg.toml

Running globsim_scale
Traceback (most recent call last):
  File "/home/stgruber/.conda/envs/globsim/bin/globsim", line 11, in <module>
    load_entry_point('globsim', 'console_scripts', 'globsim')()
  File "/home/stgruber/src/globsim/globsim/globsim_cli.py", line 41, in main
    task.main(args)
  File "/home/stgruber/src/globsim/globsim/globsim_scale.py", line 40, in main
    JRA=JRA, MERRA=MERRA)
  File "/home/stgruber/src/globsim/globsim/globsim_main.py", line 163, in GlobsimScale
    JRAsc.process()
  File "/home/stgruber/src/globsim/globsim/scale/JRAscale.py", line 78, in process
    self.times_out_nc, self.nc_pl['time'].units)
  File "/home/stgruber/src/globsim/globsim/nc_elements.py", line 86, in new_scaled_netcdf
    raise FileExistsError("File already exists: {}".format(ncfile_out))
FileExistsError: File already exists: /fs/yedoma/usr-storage/stgruber/globsim/YK/scaled/scaled_jra55_1h_scf1.5.nc
```

**Comment by nicholas512** [comment]
There is an `overwrite=true` parameter in the toml file but its obviously not hooked up yet.  I'll break that up into a separate issue and can tackle it fairly quickly

**Comment by nicholas512** [comment]
oops, didn't read the issue carefully enough.  This is one issue.
