### ISSUE TITLE
ERA5 scaling searches for wrong file

### ISSUE THREAD

**Issue by EmilieStewartJones** [geocryology/globsim#94]
searches for era5__pl_pointslist_surface.nc instead of era5_pl_pointslist_surface.nc (extra _). Creates following error: FileNotFoundError: [Errno 2] No such file or directory: b'<directory>/era5__pl_pointslist_surface.nc'

**Comment by nicholas512** [comment]
can you copy the full stack trace / error message?

**Comment by EmilieStewartJones** [comment]
Traceback (most recent call last):
  File "/home/esj555/.conda/envs/globsim/bin/globsim", line 11, in <module>
    load_entry_point('globsim==2.3.1', 'console_scripts', 'globsim')()
  File "/home/esj555/globsim/globsim/globsim_cli.py", line 97, in main
    args.func(args)
  File "/home/esj555/globsim/globsim/globsim_scale.py", line 40, in main
    JRA=JRA, MERRA=MERRA)
  File "/home/esj555/globsim/globsim/globsim_main.py", line 147, in GlobsimScale
    ERA5sc = scale.ERA5scale(sfile)
  File "/home/esj555/globsim/globsim/scale/ERA5scale.py", line 71, in __init__
    'r')
  File "netCDF4/_netCDF4.pyx", line 2321, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1885, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/fs/yedoma/usr-storage/esj555/Canoe_test/interpolated/era5__sa_siteslist.nc'

**Comment by EmilieStewartJones** [comment]
I just changed line 62 of ERA5scale.py on my local version.

**Comment by nicholas512** [comment]
ok, that seems like a good solution - can you make a pull request to update the main branch?

I think when the renalaysis / ensemble naming got updated the extra `_` got added. 34e1724583e06141d633a3e1f1a5c1689ae5717a

**Comment by EmilieStewartJones** [comment]
To be honest, I don't really know how to do that.

**Comment by nicholas512** [comment]
We'll have to do a git workshop!  No worries, I can take care of that
