### ISSUE TITLE
MERRA download error with elevation levels

### ISSUE THREAD

**Issue by EmilieStewartJones** [geocryology/globsim#96]
Error occur when running a MERRA download using the attached toml file. 

Traceback (most recent call last):
File "/home/esj555/.conda/envs/globsim/bin/globsim", line 11, in <module>
load_entry_point('globsim==2.3.1', 'console_scripts', 'globsim')()
File "/home/esj555/globsim/globsim/globsim_cli.py", line 97, in main
args.func(args)
File "/home/esj555/globsim/globsim/globsim_download.py", line 42, in main
JRA=JRA, MERRA=MERRA, multithread=args.multi)
File "/home/esj555/globsim/globsim/globsim_main.py", line 94, in GlobsimDownload
for result in (ob.retrieve() for ob in objects):
File "/home/esj555/globsim/globsim/globsim_main.py", line 94, in <genexpr>
for result in (ob.retrieve() for ob in objects):
File "/home/esj555/globsim/globsim/download/MERRAdownload.py", line 794, in retrieve
SaveNCDF_pl_3dm().saveData(data_3dmasm, data_3dmana, chunk_size, self.directory, self.elevation)
File "/home/esj555/globsim/globsim/download/MERRAdownload.py", line 101, in saveData
all_data = MERRAdownload.wind_rh_Extrapolate(all_data)
data_lev[id_interp] = data_lev[z_top]
IndexError: index 7 is out of bounds for axis 0 with size 7

File "/home/esj555/globsim/globsim/download/MERRAdownload.py", line 668, in wind_rh_Extrapolate
[config.txt](https://github.com/geocryology/globsim/files/8073119/config.txt)

**Comment by EmilieStewartJones** [comment]
Error no longer occurred when elevation range of inpts file was increased.

**Comment by nicholas512** [comment]
yay!
